spring.application.name=demo1
spring.datasource.url=jdbc:mysql://localhost:3306/book?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Thanh@21092001
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
# Hi?n th? SQL ?? debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# N?u mu?n th?y log chi ti?t h?n:
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.hibernate=INFO

#swagger-ui
springdoc.api-docs.path=/v3/api-docs
